# Import from remote git repository.
repo: https://github.com/juju/charm-helpers
# install helpers to ./hooks/charmhelpers
destination: hooks/charmhelpers
include:
    # include all of charmhelpers.core
    - core
    # all of charmhelpers.payload
    - payload
    # and a subset of charmhelpers.contrib.hahelpers
    - contrib.hahelpers:
        - openstack_common
        - ceph_utils
        - utils
