#!/bin/bash -e

# Essex-specific functions

nova_set_or_update() {
  # Set a config option in nova.conf or api-paste.ini, depending
  # Defaults to updating nova.conf
  local key=$1
  local value=$2
  local conf_file=$3
  local pattern=""

  local nova_conf=${NOVA_CONF:-/etc/nova/nova.conf}
  local api_conf=${API_CONF:-/etc/nova/api-paste.ini}
  local libvirtd_conf=${LIBVIRTD_CONF:-/etc/libvirt/libvirtd.conf}
  [[ -z $key ]] && juju-log "$CHARM set_or_update: value $value missing key" && exit 1
  [[ -z $value ]] && juju-log "$CHARM set_or_update: key $key missing value" && exit 1
  [[ -z "$conf_file" ]] && conf_file=$nova_conf

  case "$conf_file" in
    "$nova_conf") match="\-\-$key="
                  pattern="--$key="
                  out=$pattern
                  ;;
    "$api_conf"|"$libvirtd_conf") match="^$key = "
                 pattern="$match"
                 out="$key = "
                 ;;
    *) error_out "ERROR: set_or_update: Invalid conf_file ($conf_file)"
  esac

  cat $conf_file | grep "$match$value" >/dev/null &&
    juju-log "$CHARM: $key=$value already in set in $conf_file" \
      && return 0
  if cat $conf_file | grep "$match" >/dev/null ; then
    juju-log "$CHARM: Updating $conf_file, $key=$value"
    sed -i "s|\($pattern\).*|\1$value|" $conf_file
  else
    juju-log "$CHARM: Setting new option $key=$value in $conf_file"
    echo "$out$value" >>$conf_file
  fi
  CONFIG_CHANGED=True
}
